### PR TITLE
PEP8

### PR DESCRIPTION
**Pull request by Ganonmaster**
Do not merge, work in progress.

### CODE REVIEW

**Comment by Clorr** [comment]
I love it already ;-)

**Comment by deepfakes** [comment]
Hi @Ganonmaster ,

I had to rebase the whole repo because my pro credentials where appearing in some commits. You will have to rebase on the whole history on your side. 

Hopefully, it shouldn't be a big deal, but I had conflicts on Dockerfile, so maybe you will have it too...

Sorry for that

**Comment by Clorr** [comment]
I was wondering how to update my repo before being able to continue working on it...
These pages have helped:
- https://help.github.com/articles/configuring-a-remote-for-a-fork/
- https://help.github.com/articles/syncing-a-fork/

**Comment by Ganonmaster** [comment]
I'll make a new merge request with my changes. This is kind of a mess.

**Pull request closed without merging**
