### PR TITLE
Only import DLIB related modules when required and minor import relocations

### PR DESCRIPTION
**Pull request by torzdf**
DLIB is a memory hog. Firing it up every time faceswap is run can lead to memory issues. This PR changes the imports so that any DLIB related modules are only loaded when required.

I have also moved any imports within the code that I have amended (e.g. tensorflow for allow_growth) to the top, so imports are all together. 

Threading was imported twice for train.py, so this has been fixed.

I think I got them all, but let me know if not. I tried to keep this at the highest level possible.

Tested working with extract, sort, train and convert.

### CODE REVIEW

**Comment by torzdf** [comment]
ref: #311

**Comment by iperov** [comment]
I disagree with this PR.
This PR is absolutely useless.

**Comment by iperov** [comment]
stop messing code please

**Comment by iperov** [comment]
```
if FaceLandmarksExtractor is None:
      import_FaceLandmarksExtractor()
```
srsly ? so crap code

**Comment by torzdf** [comment]
Console 1:
`DISPLAY=:3 python faceswap.py train -A ./job/faces_a -B ./job/faces_b -m ./job/model_IAE -t IAE -p`

Console 2:
`python faceswap.py -h`

Without fix:
```
Traceback (most recent call last):
  File "faceswap.py", line 8, in <module>
    from lib.cli import FullHelpArgumentParser
  File "/home/user/fake/faceswap/lib/cli.py", line 7, in <module>
    from lib.FaceFilter import FaceFilter
  File "/home/user/fake/faceswap/lib/FaceFilter.py", line 3, in <module>
    import face_recognition
  File "/home/user/fake/env/lib/python3.5/site-packages/face_recognition/__init__.py", line 7, in <module>
    from .api import load_image_file, face_locations, batch_face_locations, face_landmarks, face_encodings, compare_faces, face_distance
  File "/home/user/fake/env/lib/python3.5/site-packages/face_recognition/api.py", line 24, in <module>
    cnn_face_detector = dlib.cnn_face_detection_model_v1(cnn_face_detection_model)
RuntimeError: Error while calling cudaMalloc(&data, new_size*sizeof(float)) in file /home/user/fake/dlib/dlib/dnn/gpu_data.cpp:195. code: 2, reason: out of memory
```
With fix:
```
usage: faceswap.py [-h] {extract,train,convert} ...

positional arguments:
  {extract,train,convert}
    extract             Extract the faces from a pictures.
    train               This command trains the model for the two faces A and
                        B.
    convert             Convert a source image to a new one with the face
                        swapped.

optional arguments:
  -h, --help            show this help message and exit

```


Anything else useful you want to add?

**Comment by iperov** [comment]
so you won +100mb of VRAM by sacrificing **consistency** of the code ?

this is sucks:
```
+face_recognition = None
+FaceLandmarksExtractor = None
+
+def import_face_recognition():
+    ''' Import the face_recognition module only when it is required '''
+    global face_recognition
+    import face_recognition
+
+def import_FaceLandmarksExtractor():
+    ''' Import the FaceLandmarksExtractor module only when it is required '''
+    global FaceLandmarksExtractor
+    import lib.FaceLandmarksExtractor
+    FaceLandmarksExtractor = lib.FaceLandmarksExtractor

     def sort_face_cnn(self):
+        if FaceLandmarksExtractor is None:
+            import_FaceLandmarksExtractor()
```

**Comment by torzdf** [comment]
So. Nothing constructive to add. There's a surprise.

**Comment by iperov** [comment]
You just ruining the code **and make it hard to develop new additions.**
We are in constant developing and researching new features, why optimising ?

Just buy 4GB card, or disable aero in windows 10, if you dont have last 100mb vram.

**Comment by torzdf** [comment]
LOLOLOLOLOL. I'm running a GTX 1080 on linux server.

But, ok. Making the programme generate errors just passing the help command is definitely a fantastic user experience. I bow to your vastly superior design ethic.

**Comment by iperov** [comment]
**GTX 1080 on linux server**
lol, and still not enough ram? 

Yes, architecture of faceswap is bad, but you make it worse

**Comment by JayantPythonLover** [comment]
@iperov I often find you being so extremely rude to people trying to contribute -- especially if you don't agree with the changes. There is a nicer way of saying things if you disagree. You need to learn how to do that and not behave like a tantrum throwing child.

In simpler words you might understand, stop being a fucking idiot.

@torzdf 

I like what you are trying to do. As someone who has a Titan and still faces OOM issues, I most certainly welcome the optimizations. There are various parts of the code that handle memory in a horrendous fashion and need dealing with.

I cannot test out the code right now but from what I see of the changes, you seem to be on the right track.

I'll run for all situations later and see if any more changes need to be made. Good job so far.

**Comment by iperov** [comment]
JayantPythonLover , nop, I dont like only fixes that looks like sewn six finger :D

**Comment by torzdf** [comment]
@JayantPythonLover 

> There are various parts of the code that handle memory in a horrendous fashion and need dealing with.
> 
> I cannot test out the code right now but from what I see of the changes, you seem to be on the right track.
> 
> 

In fairness, if I were building from scratch, this certainly isn't how I would go about approaching this problem, however, my end goal was to be able to run more than one faceswap instance (one for gpu task and one for non-gpu) and to do this with the minimum amount of code change.

If someone wants to go ahead and fix the code in a more robust manner (which should probably be the end goal), then please be my guest. In the mean time this is a band aid, which works.

**Comment by bryanlyon** [comment]
This PR is currently the best solution we have to a horrible set of problems.  Ideally, we'd be importing as needed into each module.  Python explicitly allows you to import in logic, and as long as everything is kept near the top, I have no problem with avoiding imports that aren't necessary until later in the code.  I almost did the same for the multi_gpu_model when I implemented it, but found that it was a minimal effect when -g wasn't called.

In this case, dlib immediately grabs control of the GPU and loads it up with quite a bit of nonsense (In my running it's actually closer to 340MB though it varies from time to time.  On a 4gb card, that's 10% of the memory and makes running the original model impossible on those cards.  Seeing as the Original model was designed for 4gb of vram, I believe that a solution is needed.  Unless we refactor the entire project (including measures such as moving the argument parsing into it's own module file with no imports of external modules) this is the best solution available to us.

I support this PR.  I also recommend we undergo planning for a refactor of the main code.

**Comment by iperov** [comment]
@Clorr , 
I suggest close all PRs and start global refactoring.
Lets stop ruining the code such as this PR.

**Comment by iperov** [comment]
@Clorr @oatssss @gdunstone 
I suggest close all PRs and start global refactoring.
Lets stop ruining the code such as this PR.

my eyes are bleeding
```
 if face_recognition is None:
            import_face_recognition()

    def sort_face_dissim(self):
        if face_recognition is None:
            import_face_recognition()
        
    def sort_face_cnn(self):
        if FaceLandmarksExtractor is None:
            import_FaceLandmarksExtractor()

```

**Comment by bryanlyon** [comment]
@iperov I don't know why you're so against those imports, they're all perfectly reasonable and understandable.  While a refactor would be cleaner, it's a long way out.  An unplanned refactor is worse than hacking.

**Comment by torzdf** [comment]
@JayantPythonLover I can't replicate. Can you print console output please, this is what I get:
```
(env) user@user-ubuntuVM:~/fake/faceswap_torzdf$ python faceswap.py extract -i /mnt/fakes/Masters/B/subject/test/ -o /mnt/fakes/Masters/B/subject/test_faces -D all -ae
Input Directory: /mnt/fakes/Masters/B/subject/test
Output Directory: /mnt/fakes/Masters/B/subject/test_faces
Filter: filter.jpg
Using json serializer
Starting, this may take a while...
Loading Extract from Extract_Align plugin...
  0%|                                                                                                                                                        | 0/15 [00:00<?, ?it/s]/home/user/fake/env/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. Infuture, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Info: initializing keras model...
2018-03-27 00:03:14.734894: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-03-27 00:03:14.745142: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1331] Found device 0 with properties:
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.7715
pciBusID: 0000:05:00.0
totalMemory: 7.93GiB freeMemory: 5.99GiB
2018-03-27 00:03:14.745202: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1410] Adding visible gpu devices: 0
2018-03-27 00:03:16.426265: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-03-27 00:03:16.426862: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0
2018-03-27 00:03:16.426895: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N
2018-03-27 00:03:16.427638: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1021] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5780 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:05:00.0, compute capability: 6.1)
WARNING:tensorflow:From /home/user/fake/env/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py:1349: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:39<00:00,  2.66s/it]
Alignments filepath: /mnt/fakes/Masters/B/subject/test/alignments.json
Writing alignments to: /mnt/fakes/Masters/B/subject/test/alignments.json
-------------------------
Images found:        15
Faces detected:      15
-------------------------
Done!
```

Output folder has 15 faces in it.

**Comment by torzdf** [comment]
And I just tested with the latest commits merged in, just in case, and I still get a successful extract. To be honest, I'm not sure why anything I've changed should impact on those two switches.

**Comment by torzdf** [comment]
So is anyone else able to replicate? I have tested extensively now and all seems fine.

Can we merge or close please.

**Comment by bryanlyon** [comment]
I believe that this is ready to merge.  It helps run the Original model on 4gb cards.

**Pull request merged**
