### PR TITLE
Histogram matching with option -mh

### PR DESCRIPTION
**Pull request by oatssss**
cv2's seamless clone already does colour correction, but it sometimes doesn't act the way you want. Here's another option to try.

### CODE REVIEW

**Comment by ruah1984** [comment]
i thought it already merge in https://github.com/deepfakes/faceswap/pull/217 ?? any way thanks for everything

**Comment by oatssss** [comment]
#217 isn't merged yet so this one can go in separately if people want

**Comment by Apollo122** [comment]
@oatssss can we use this together with seamless clone to remove the flicker? If we specify -seamless true and -mh true will it first use seamless clone then mh to correct the flicker?

**Comment by oatssss** [comment]
@Apollo122 it'll use seamless, then match the histogram afterwards so it should reduce flickering.

**Comment by oatssss** [comment]
@Apollo122 when seamless is on, seamless clone is the last step in the process to patch it back into the image. Seamless does not use a facehull mask to patch it back in since cv2 handles creates its own mask automatically based on context. What I can do is if both seamless and histogram matching are on, after the seamless clone, pass it through to be color-corrected then hand it over to the regular facehull mask to patch it back in, instead of seamless cloning it in. Trying to seamless clone it back in after color-correction might just bring the flicker back, not sure.

**Comment by Apollo122** [comment]
Great! It would be a nice feature. Seamless clone is useful except flickering but we can minimize it with hm

**Comment by oatssss** [comment]
Closing since this was merged alongside #217.

**Comment by Apollo122** [comment]
@oatssss any progress on seamless+hm ? I will train a new model with GAN and and curious what the results would be

**Comment by kvrooman** [comment]
I had an error thrown for me if i use the -mh flag after the -m flag when i convert.  Can't find model etc or something...  It worked if I put the -mh flag before the -m flag in the command line though. Might be useful to change the flag name to something more unique ( -MH ? ) or do you know why that would have happened for me?

**Pull request closed without merging**
