### PR TITLE
frame-range option for convert

### PR DESCRIPTION
**Pull request by gdunstone**
this option allows you to define multiple frame ranges to process.

to convert the frames 0 to 50 and 100 to end and still write out unconverted frames:

`./faceswap.py convert -s -fr min-50 100-max`

to convert frames 0 to 50 and 100 to 200 and discard any unconverted frames:

`./faceswap.py convert -s -fr 0-50 100-200 --discard-frames`

### CODE REVIEW

**Comment by Clorr** [comment]
Hi, I just read your code as I'm continuing on the GAN plugin. I just noticed something that would be a better practice in order to keep the code clean.

In the code below:
```

    def convert(self, converter, item):
        try:
            (filename, image, faces) = item
            skip = False
            try:
                if self.frame_ranges is not None:
                    # grab the index with last number regex
                    idx = int(self.imageidxre.findall(filename)[0])
                    # only skip if the current index is not between any of the frame ranges.
                    skip = not any(map(lambda b: b[0]<=idx<=b[1], self.frame_ranges))
            except:
                # if we error, dont skip
                skip = False

            if not skip: # process as normal
                for idx, face in faces:
                    image = converter.patch_image(image, face)

            output_file = self.output_dir / Path(filename).name
            if self.arguments.discard_frames and skip:
                return
            cv2.imwrite(str(output_file), image)
        except Exception as e:
            print('Failed to convert image: {}. Reason: {}'.format(filename, e))
```

it would be better to avoid having the logic inside the main function, because if add more and more logic here, it will end up with a big messy function. It would be better to have something like:

```
    def convert(self, converter, item):
        try:
            (filename, image, faces) = item
            if not checkSkip(filename): # process as normal
                for idx, face in faces:
                    image = converter.patch_image(image, face)

            output_file = self.output_dir / Path(filename).name
            if self.arguments.discard_frames and skip:
                return
            cv2.imwrite(str(output_file), image)
        except Exception as e:
            print('Failed to convert image: {}. Reason: {}'.format(filename, e))
```
and define `checkSkip` in an outside function ;-)

**Comment by gdunstone** [comment]
You are totally right about checkSkip needing to be a separate func.

**Comment by gdunstone** [comment]
I think this is ok?

I feel like checking a variable is less taxing than calling a func here.

**Comment by Clorr** [comment]
Yes, it's ok like that ;-)

Adding an intermediate var has no impact on the speed, if you do `if not func()`, there will always be an internal var created. Also calling a function has a cost, but it is very small (typically around 0.1 microsecond).

The only cases where you would prefer inlining the code (ie. not creating a function) is in places where the code is called millions of times or more.

For a loop like this, that is called once per image, the performance impact is totally unnoticeable and it is much better to keep code clean

**Pull request merged**
