### PR TITLE
Added keras version of FAN for plaidml backends

### PR DESCRIPTION
**Pull request by kilroythethird**
This PR adds a keras version of the FAN aligner to support plaidml backends.
I currently import keras in the global scope. If this should lead to multiprocessing problems we can move the import behind a backend check, but i'd prefer not to if we don't need to.

This is not tested with multithreading/processing nor with an nvidia card nor on windows.
Please test if it break the "normal" behaviour.

### CODE REVIEW

**Comment by torzdf** [comment]
Could you put this in as a separate plugin please? (fan_plaidml or fan_amd maybe). I'd rather have the separation in case of changes/running into issues down the line.

**Comment by kilroythethird** [comment]
Sure. Sounds like the better idea actually.
Gotta love the plugin system.

**Comment by torzdf** [comment]
I have added a `supports_plaidml` flag that defaults to False for extract plugins. You may want to push a change to your initialization script to set it to True. I will then check out this PR and see about getting it integrated asap.

Want to close the book on plaidML support

**Comment by kilroythethird** [comment]
Sorry for the delay.
I also changed the "Using GPU:" log output in plaidml_tools to output the device ids again instead of the index. Hope that was ok.

**Comment by torzdf** [comment]
I've split this off to a new plaidML branch as there are still a few bugs I'm finding around the plaidML implementation (logging on extract etc.), and I want to be able to fix those with this in place.

I will merge the branch directly back to staging to ensure that you maintain your contrib status.

Good work. Works great on my test AMD rig. Still need to do some testing on Nvidia platform.

**Comment by kilroythethird** [comment]
Its basically just the old implementation of FS tbh ;)

**Pull request merged**
