### PR TITLE
Add GNU General Public License v3.0

### PR DESCRIPTION
**Pull request by dfaker**

### CODE REVIEW

**Comment by dfaker** [comment]
Adding multiple assignees to get the chance wide range of objections on this from all contributors.

**Comment by ruah1984** [comment]
You forget shaoanlu.

**Comment by dfaker** [comment]
@shaoanlu isn't a named collaborator but his objections are welcome.

**Comment by gdunstone** [comment]
I approve!!

**Comment by dfaker** [comment]
That would seem to be a lack of objections.

**Pull request merged**
