### PR TITLE
Adding new tool effmpeg ("easy"-ffmpeg) with gui support. Extend gui functionality to support filetypes. Re-opening PR.

### PR DESCRIPTION
**Pull request by AbysmalBiscuit**
I have fixed the issues mentioned by @torzdf in the previous PR.

Any and all feedback is welcome.

### CODE REVIEW

**Comment by AbysmalBiscuit** [comment]
@torzdf no worries I'll resolve the conflicts. :)

**Comment by AbysmalBiscuit** [comment]
When I resolved the merge conflicts I introduced a few small bugs, I'll quickly sort them out and push a new commit.

**Comment by torzdf** [comment]
So, I'm testing on the GUI.

- General -  I suggest you use the -hide_banner flag to suppress some of the unneeded ffmpeg build info.


- Extract - All good.
- gen-vid - All good.
- get-info - All good, but 
- get-fps - Is this meant to output to the console? It doesn't for me.
image
- mux-audio: Traceback error:
```
Loading...
Please backup your data and/or test the tool you want to use with a smaller data set to make sure you understand how it works.
Traceback (most recent call last):
File "/home/matt/fake/faceswap/tools.py", line 40, in <module>
ARGUMENTS.func(ARGUMENTS)
File "/home/matt/fake/faceswap/tools/effmpeg.py", line 446, in process_arguments
self.process()
File "/home/matt/fake/faceswap/tools/effmpeg.py", line 460, in process
action(**kwargs)
File "/home/matt/fake/faceswap/tools/effmpeg.py", line 553, in mux_audio
ff = FFmpeg(inputs=_inputs, outputs=_outputs)
File "/home/matt/fake/env/lib/python3.5/site-packages/ffmpy.py", line 56, in __init__
self.cmd = subprocess.list2cmdline(self._cmd)
File "/usr/lib/python3.5/subprocess.py", line 751, in list2cmdline
needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'DataItem' is not iterable
Process exited.
```
image

rescale - All good
rotate - All good, although my preference would be to explicitly state names rather than numbers for transpose, but understand this may be difficult to implement for cli reasons

**Comment by AbysmalBiscuit** [comment]
@torzdf thanks for testing! 
I'll push a commit today fixing the bugs you found.

**Comment by AbysmalBiscuit** [comment]
@torzdf I've fixed the issues you had found.

As for putting the full name of the effect for transpose, I have come up with a solution and will make another patch. Although it may make explaining the cli a bit more confusing.

**Comment by torzdf** [comment]
> I have come up with a solution and will make another patch. Although it may make explaining the cli a bit more confusing.

I wouldn't worry too much. Cli should always take priority

**Comment by AbysmalBiscuit** [comment]
Actually I hadn't fully thought it through, and it will be fairly simple to explain in the help doc whow it works.

It will be something along the lines of:
```python
arguments_list.append({
"opts": ('-tr', '--transpose'),
"choices": ("(0, 90CounterClockwise&VerticalFlip)", 
            "(1, 90Clockwise)", "(2, 90CounterClockwise)", 
            "(3, 90Clockwise&VerticalFlip)", "None"),
"action": HandleTranspose,
"dest": "transpose",
"default": "None",
"help": """Transpose the video. If transpose is 
           set, then rotate will be ignored. For cli
           you can enter either the number or the
           long command name, e.g. 
           -tr 0 or -tr 90Clockwise"""
})
```

**Comment by Allan-Nava** [comment]
Nice feature

**Comment by AbysmalBiscuit** [comment]
@torzdf I'd say it's ready for testing.

**Comment by torzdf** [comment]
Sorry for the delay, been a bit busy of late.

Is there any way to implement this without importing psutil? I'm just a bit wary of the growing list of non-standard imports.

**Comment by AbysmalBiscuit** [comment]
No worries about the delay. 

I'll look into it today. `psutil` just makes it really easy to get all the child processes' IDs, but I could probably write a method that would retrieve it.

**Comment by AbysmalBiscuit** [comment]
I've reformatted it so it is no longer dependent on `psutil`, by having it start effmpeg as a group subprocess (via a list of commands that should be treated as group subprocesses, hence allowing for easy future extension).

However I discovered a bug wherein the faceswap.py functions don't recognize `.bmp` files as images, hence I want to add `.bmp` as a valid file extension before commiting and pushing.

**Comment by torzdf** [comment]
No probs!

**Comment by AbysmalBiscuit** [comment]
@torzdf I've fixed the issues. While looking for where the image extensions list was I stumbled across some other small problems in a few files, so I fixed those as well.

**Comment by torzdf** [comment]
Ok, I'm finally merging this. There are some tweaks I would make, but nothing that is breaking. Good job man 👍

**Comment by torzdf** [comment]
@AbysmalBiscuit Just out of interest, what was your thinking behind redirecting tqdm to stdout?

**Pull request merged**
