### PR TITLE
color match A and B set images + performance improvement

### PR DESCRIPTION
**Pull request by avilv**
improve performance by pre-loading images before iteration.

i noticed FakeApp does this better by matching the colors between the sets so i added that back in
also avoiding cv2.readim on each iteration is a much better idea than doing that repeatedly
 (HDD's are slow)
i'm seeing a nice performance improvement from this as-well

### CODE REVIEW

**Comment by LordVulkan** [comment]
What if you don't have enough memory to allocate all images?

**Comment by subzerofun** [comment]
@avilv  With how many images in folder A and B combined did you test this?
Do the images now get stored in RAM or on the GPU? I currently have a project where folder A has ~4000 face images, folder B also ~4000. I'm a little reluctant to test this without knowing if my hardware can handle pre-loading 8000 images :-)

**Comment by subzerofun** [comment]
OK 8000 images _are_ too much. Memory (24 GB) full, swap files piling up. Terminal freezes, several Apps crash – but the Python process with tensorflow is still running, allocating space 😆.

**Comment by Clorr** [comment]
Has pros and cons, tha fact it loads all files at the beginning is a problem, but you are right, we still can do better for that part...

**Pull request closed without merging**
