### PR TITLE
Gitignore and requirements.txt

### PR DESCRIPTION
**Pull request by Ganonmaster**
Small quality of life improvements like pip requirements files. Specific versions listed are the ones that I used for testing, but improvements and suggestions are most welcome.

- Added a basic `.gitignore` with a few windows/mac and python presets. (perhaps add data/model directories too so people don't accidentally commit those)
- Added `requirements.txt` and `requirements-gpu.txt`

### CODE REVIEW

**Comment by deepfakes** [comment]
Hi, thanks for the PR!

It seems the last line of the Dockerfile is a result of a conflict. 

Can you clean it and test on you side ?

I'll happily merge after that!

**Comment by deepfakes** [comment]
Works fine, thanks!

Do you want to be added as collaborator ?

**Comment by Ganonmaster** [comment]
Yes, I would like to add more usability improvements this week.

**Comment by deepfakes** [comment]
Here we go!

You should have received an invite.

You'll be able to push, and hopefully to merge Pull Requests.

**Pull request merged**
