### PR TITLE
Add debugging option for drawing landmarks on face extraction.

### PR DESCRIPTION
**Pull request by LordVulkan**

### CODE REVIEW

**Comment by iperov** [comment]
more logical place debug argument at end of list
`def extract(self, image, face, size, debug_landmarks = False):`

**Comment by LordVulkan** [comment]
False as default value is redundant as it is already specified in the arguments parser.

**Comment by iperov** [comment]
Think as modular programming, is_debug_landmarks actually optional value and doesnt affect to `extract` major behaviour

**Comment by LordVulkan** [comment]
I have updated the base code from master and moved the drawing code to extract script, but I don't know if I did the merge correctly. Please checkout.

**Pull request merged**
