### PR TITLE
Config modifications and upgrades

### PR DESCRIPTION
**Pull request by kvrooman**
- Better docstrings / descriptions of all options in training global config options
- Implemented additional common loss functions in a drop-down selection
    - MAE
    - MSE
    - Logcosh
    - SSIM
    - GMSD
    - Total Variation
    - Smooth L1
    - L-inf norm
- Moved DSSIM loss choices in each model to the above global drop-down
- Enabled drop-down loss selection for mask ( as well as image )
- Streamlined constructions of image/mask loss functions in train/_base.py
- ~~Moved 'No flip' option to config~~ Keep flipping in CLI for now as discussed
- Renamed PenalizedLoss to Mask_Penalized_Loss to be more descriptive
- No augmentation toggle now available for training ( desire is to modify preview to pull from a generator with no augmentations )
- Set clipnorm to False by default for Unbalanced... believe that issues were fixed with a PR on ICNR
- Linting of losses.py
- Linting of layers.py
- Addition of GlobalMinPooling and GlobalStdDevPooling to Layers
- Minor cleanup on IAE

-TODO:
    - ~~Total Variation now has a hard coded shape of 64x64x3. Fix TF shape assertion error~~

### CODE REVIEW

**Comment by torzdf** [comment]
Sorry, there are conflicts now due to #688 getting merged. Could you resolve conflicts and I'll review + merge

**Comment by torzdf** [comment]
re: "No augmentation toggle" I'd recommend removing this as an option and just make sure the previews don't go through augmentation. I don't think there is any reason why a user wouldn't want this.

**Comment by torzdf** [comment]
I'm really sorry dude. I introduced conflicts again :/

I will look at this PR next, once resolved.

**Comment by kvrooman** [comment]
@torzdf  resolved

**Comment by kvrooman** [comment]
@torzdf made some additional linting and error fixes from the additional items that have crept in

**Pull request merged**
