### PR TITLE
sorttool argument changes and added -by face 

### PR DESCRIPTION
**Pull request by iperov**
changed arguments
now valid arguments:
-by blur
-by hist (default)
-by face

'by face' helps sort faces extracted from internet photos

example:

-by hist:
fsviewer_2018-03-11_19-06-12

-by face:
fsviewer_2018-03-11_19-09-43

### CODE REVIEW

**Comment by i5L4NDOF5T4BiLiTY** [comment]
Works even better than version 1, -by face to check no other faces sneaked in there, then -by blur to get rid of the trash, then -by hist to look over the dataset in all its optimised glory.

**Comment by Clorr** [comment]
Ok to merge this. One request though. Can you put this file in a `tools/` folder and name it a bit more explicitly (something like sort_extracted.py, or something you find relevant)?

**Comment by iperov** [comment]
@Clorr i dont think it good idea, because following this logic, \scripts\ also can be run directly, but they cant

**Comment by bryanlyon** [comment]
This is no different from any other linux program's directory layout; tools/ is implied to refer to self-contained tools that help the project without but other folders are usually utilities or sub-files used by the main program.  That said, a simple catchall added to files in scripts/ could warn users that they're not directly executable.

**Comment by iperov** [comment]
bryanlyon also other directories same warn.

better solution is move all prog to 
src\
then tools\ is ok

**Comment by Enyakk** [comment]
I noticed that the -by face sorting has problems with faces (side profiles, low angles) originally aligned+detected by CNN, resulting in a semi-random order. That is because face_recognition by default uses "hog" for face_encodings, so those "CNN-exclusive" faces fail when re-detected by HOG.

I was unsuccessful to modify face_recognition to engage CNN-mode. Maybe it's possible to re-use the alignments.json or do they not contain the necessary information?

**Comment by iperov** [comment]
@Enyakk 5 point model used in faceencodings

```
def face_encodings(face_image, known_face_locations=None, num_jitters=1):
    raw_landmarks = _raw_face_landmarks(face_image, known_face_locations, model="small")
```

there is no chance to use 68 point model outside the lib face_recognition.

Also I dont know how landmarks transformed to 128D vector for compare

https://github.com/davisking/dlib/blob/master/tools/python/src/face_recognition.cpp compute_face_descriptors

**Comment by Enyakk** [comment]
As a test I successfully enabled the 68 point model by directly putting face_recognition into the same directory as sorttool.py and changing the default predictor in api.py to "large".

`def face_encodings(face_image, known_face_locations=None, num_jitters=1):'
...
'raw_landmarks = _raw_face_landmarks(face_image, known_face_locations, model="large")`

**Comment by iperov** [comment]
@Enyakk and what ? you cant change the lib.

**Comment by iperov** [comment]
@bryanlyon and how to import lib from tools\ ?

**Comment by Clorr** [comment]
@iperov you have to use:
`from ..lib.foo import foo, bar`
You have to add `.` in front of path to go to upper dir

**Comment by iperov** [comment]
you think this is good architecture ? :)

**Comment by Clorr** [comment]
Fair enough for a utility. If you want to make better architecture, you can add a tools.py at the root and make it run with a `tools.py sort`

**Comment by Clorr** [comment]
(and this way your imports will be relative to root folder)

**Pull request merged**
