### PR TITLE
add ru locale

### PR DESCRIPTION
**Pull request by andentze**
After months of convincing myself to do this, and hours of work lost, I present to you. The (probably) official RU locale for Faceswap.

I _might_ need to double-check if the translation if alright, but I need this to be pushed as either a different branch, or something else.

It's been fun to work on this though.

### CODE REVIEW

**Comment by long369486562** [comment]
I generated Simplified Chinese, but it doesn't display properly

**Comment by long369486562** [comment]
image

**Comment by long369486562** [comment]
@andentze @torzdf Can you give some tips on how to solve the problem I raised?

**Comment by torzdf** [comment]
> @andentze @torzdf Can you give some tips on how to solve the problem I raised?

Raise it as a PR and I can take a look

**Comment by long369486562** [comment]
@torzdf Sorry, I can only simply use GITHUB, I don't fully understand what you mean, can you elaborate on that?

**Comment by torzdf** [comment]
Sure, have a look here:
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

It may seem intimidating at first, but it really isn't too difficult. Once done, I can checkout and review the code, and we can merge your translations in to the main project, which would be very useful for Chinese users (and you would become a contributor)

**Comment by long369486562** [comment]
@torzdf   https://github.com/long369486562/faceswap/tree/zh-cn-locales/locales
I'm not sure I'm doing it right, but can make the code you see to implement

**Comment by long369486562** [comment]
@torzdf Brother, looking forward to your reply

**Comment by torzdf** [comment]
First thing I would suggest is to update Faceswap. There was an issue with locales not displaying correctly in Windows, which I fixed yesterday.

**Comment by long369486562** [comment]
ok,

**Pull request merged**
