### PR TITLE
frame-range changes

### PR DESCRIPTION
**Pull request by gdunstone**
feedback from Clorr

https://github.com/deepfakes/faceswap/pull/90#issuecomment-362309166

### CODE REVIEW

**Comment by gdunstone** [comment]
I think this is allright.

**Comment by gdunstone** [comment]
@Clorr sorry if I rely on you too much. I normally work on private repos.

**Comment by Clorr** [comment]
No problem, I'm not that used to public repos either. And I prefer a living repo than a too strict one where nothing moves on ;-)

**Comment by gdunstone** [comment]
lol yep. Also I'm super keen for GAN.
Haven't looked much at it yet but I'm excited. XD

**Pull request merged**
