### PR TITLE
Add Apple Silicon (M1) support

### LINKED ISSUE #1143: Disabling AMD and CUDA sets backed to "cpu" in config, but running faceswap -h still tries to load CUDA
Turning off all GPU related config items during setup does create config/.faceswap, which contains {"backend": "cpu"}.

However, running faceswap.py -h throws an exception and terminates the program:

Setting Faceswap backend to CPU
Traceback (most recent call last):
  File "faceswap.py", line 6, in <module>
    from lib.cli import args as cli_args
  File "/Users/mrfredsmoothie/software/faceswap/lib/cli/args.py", line 13, in <module>
    from lib.gpu_stats import GPUStats
  File "/Users/mrfredsmoothie/software/faceswap/lib/gpu_stats.py", line 17, in <module>
    import pynvx  # pylint: disable=import-error
ModuleNotFoundError: No module named 'pynvx'

Why set the backend to CPU and then choke trying to display options?

**To Reproduce**
1. configure a lack of GPU support
2. try to use the -h option to list available options and commands

**Expected behavior**
Don't try to load GPU info if no GPU support is configured

**Desktop (please complete the following information):**
 - OS: MacOS X 11.2.3 (M1 arm64)
 - Python Version Python 3.8.8
 - Conda Version 4.10.0
 - Commit ID f60eaee

### LINKED ISSUE #1197: Please Support for Apple M1 pro/max
As we know, Apple release New silicon named M1 pro/max.

It has  powerful GPUs and CPUs.

Is there any chance to run FaceSwap on new Mac book pro?

### PR DESCRIPTION
**Pull request by geewiz94**
This is using:
- Python 3.9
- Tensorflow 2.8
- GPU support via Metal

I've successfully tested extract/training/convert on a MacBook Pro with the M1 Pro chip.

As far as I can tell, all models seem to be working, ~~except for:~~
- Phaze-A ~~(error with most presets, except Stojo, where the previews turn white?). Will do some more tests.~~ Works, Stojo preset might need to be adjusted.
- Unbalanced: ~~Not quite sure, as I don't have any experience with it (the previews are white during the first couple of iterations?). Need to test for a longer duration.~~ Works with lower learning rate!

Fixes #1143
Fixes #1197

Credit goes to @daniellivingston for most of this!

### CODE REVIEW

**Comment by daniellivingston** [comment]
Thanks for opening this PR! Nice work!

**Comment by daniellivingston** [comment]
> Hello @geewiz94! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:
> 
> * In the file [`lib/gpu_stats.py`](https://github.com/deepfakes/faceswap/blob/a0d38c2d687b2826fac13150a2e344065378effe/lib/gpu_stats.py):
> 
> > [Line 17:30](https://github.com/deepfakes/faceswap/blob/a0d38c2d687b2826fac13150a2e344065378effe/lib/gpu_stats.py#L17): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> 
> * In the file [`lib/metal/__init__.py`](https://github.com/deepfakes/faceswap/blob/a0d38c2d687b2826fac13150a2e344065378effe/lib/metal/__init__.py):
> 
> > [Line 3:14](https://github.com/deepfakes/faceswap/blob/a0d38c2d687b2826fac13150a2e344065378effe/lib/metal/__init__.py#L3): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> > [Line 6:1](https://github.com/deepfakes/faceswap/blob/a0d38c2d687b2826fac13150a2e344065378effe/lib/metal/__init__.py#L6): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> > [Line 11:5](https://github.com/deepfakes/faceswap/blob/a0d38c2d687b2826fac13150a2e344065378effe/lib/metal/__init__.py#L11): [E301](https://duckduckgo.com/?q=pep8%20E301) expected 1 blank line, found 0
> > [Line 14:1](https://github.com/deepfakes/faceswap/blob/a0d38c2d687b2826fac13150a2e344065378effe/lib/metal/__init__.py#L14): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> > [Line 20:1](https://github.com/deepfakes/faceswap/blob/a0d38c2d687b2826fac13150a2e344065378effe/lib/metal/__init__.py#L20): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> > [Line 28:1](https://github.com/deepfakes/faceswap/blob/a0d38c2d687b2826fac13150a2e344065378effe/lib/metal/__init__.py#L28): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> > [Line 29:5](https://github.com/deepfakes/faceswap/blob/a0d38c2d687b2826fac13150a2e344065378effe/lib/metal/__init__.py#L29): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> > [Line 38:5](https://github.com/deepfakes/faceswap/blob/a0d38c2d687b2826fac13150a2e344065378effe/lib/metal/__init__.py#L38): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> > [Line 40:1](https://github.com/deepfakes/faceswap/blob/a0d38c2d687b2826fac13150a2e344065378effe/lib/metal/__init__.py#L40): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> > [Line 43:1](https://github.com/deepfakes/faceswap/blob/a0d38c2d687b2826fac13150a2e344065378effe/lib/metal/__init__.py#L43): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> > [Line 46:1](https://github.com/deepfakes/faceswap/blob/a0d38c2d687b2826fac13150a2e344065378effe/lib/metal/__init__.py#L46): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> > [Line 49:1](https://github.com/deepfakes/faceswap/blob/a0d38c2d687b2826fac13150a2e344065378effe/lib/metal/__init__.py#L49): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> > [Line 52:1](https://github.com/deepfakes/faceswap/blob/a0d38c2d687b2826fac13150a2e344065378effe/lib/metal/__init__.py#L52): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> > [Line 56:1](https://github.com/deepfakes/faceswap/blob/a0d38c2d687b2826fac13150a2e344065378effe/lib/metal/__init__.py#L56): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> > [Line 59:1](https://github.com/deepfakes/faceswap/blob/a0d38c2d687b2826fac13150a2e344065378effe/lib/metal/__init__.py#L59): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> > [Line 65:62](https://github.com/deepfakes/faceswap/blob/a0d38c2d687b2826fac13150a2e344065378effe/lib/metal/__init__.py#L65): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

I think all of these issues can be resolved with [Black](https://github.com/psf/black).

**Comment by torzdf** [comment]
Thanks for this PR. I'm probably going to create another branch to merge this into whilst it is tested (I do not possess an M1 Mac, so cannot do much testing myself) and so I can refactor a little bit around the multiple backends that FS will support (also I would prefer not to remove the Nvidia/Apple combo. It is likely to be a very rare use case, but may still be in use by some users).

RE: models turning white - try lowering the learning rate to see if you can get things training that way. Interesting about Phaze-A... I would expect the StoJo preset to be the one which doesn't work, as the others are mostly just recreations of existing models.

Also, if you could fix up the Linting errors, that would be appreciated. Just helps to keep with code consistency. I wouldn't recommend using Black, as it's a bit OTT imho.

If you feel up to creating an install script, that would also be appreciated. I understand if not, but it shouldn't be that hard using the linux install script as a base https://github.com/deepfakes/faceswap/blob/master/.install/linux/faceswap_setup_x64.sh

Otherwise I will look to review more thoroughly in the coming days.

**Comment by torzdf** [comment]
You may want to hold fire on any linting etc. I am going to refactor the GPUstats section for better class inheritance rather than the myriad of if/else statements, and also try to bring that section of code a bit more up to date, as it is now fairly old. It *should* then be fairly trivial to rewrite this code a bit to inherit from the base GPUStats class.

**Comment by geewiz94** [comment]
Ok great, Unbalanced is now giving me results using a lower learning rate!
I've also merged upstream changes and this seems to have fixed the NoneType error for legacy presets in Phaze-A! Still not sure about Stojo: how many iterations does it usually take before a face starts to appear in the preview?

**Comment by CaffreyR** [comment]
Hi, I am working it on m1 pro too! But how do you fix the pynvx is not working? @geewiz94

**Comment by torzdf** [comment]
@daniellivingston @geewiz94 Ok, I have refactored gpu_stats into it's own package. This means that different GPU backends will get dynamically loaded depending on the faceswap backend in use. The unfortunate side effect is that this means you now have conflicts to be resolved. On the plus side it removes the issue of the pynvx dependency, as that will now only be loaded if the backend is Nvidia running on an Apple machine. 

As mentioned before, updating you code should not be too difficult. Please use the backend name 'applem1' so that it is easily distinguishable from Apple Intel machines. It should be fairly obvious what needs to be done by overriding the NotImplemented methods from the base GPUStats class, but any problems, let me know.

**Comment by geewiz94** [comment]
@torzdf Thanks, I'll take a look!
Phaze-A with non-original Enc Arch seems to work after all, I had to change Stojo to use efficientnet_v2_s and set Enc scaling to 50.

Global settings set to:
- Learning rate: 4.7e-5
- Epsilon exponent: -5
- Mixed precision: off

**Comment by geewiz94** [comment]
Merged and tested, seems to be working! Hope the code is okay. I'm not too sure about error handling during Metal initialization.

**Comment by torzdf** [comment]
Ok, cool. Thanks! I'll probably create a branch for this and merge it there to move a couple of bits and pieces around. As there is not much else to do, it will be probably be quicker than reviewing/feeding back.

Once done, I'll get you to do some final testing before merging to master (don't have an M1 to test with).

Thanks for the contribution :)

**Comment by torzdf** [comment]
@geewiz94 Ok, I have done my changes to the [m1](https://github.com/deepfakes/faceswap/tree/m1) branch. If you could test that all works as expected, I'll get this merged into Master

**Comment by geewiz94** [comment]
@torzdf Works great! Tested extract/convert and training with Phaze-A and dfl_sae. Thanks for all the work!

**Comment by CaffreyR** [comment]
image
@geewiz94 Hi! I test the code following your instruction, but it went wrong when I try to run this command, _python faceswap.py train -A ./tom -B ./lee -m ./weight -p_, and it report crash!

**Comment by torzdf** [comment]
@CaffreyR Please add new issues in the issues section, or on our forums (https://forum.faceswap.dev/). Also please provide the crash report as per the instructions given.

However, on the small screen grab you have given, it looks like you are trying to run training on images that have not been extracted by Faceswap.

**Comment by CaffreyR** [comment]
Sorry, I thought it was one of the test situation of the testing branch. Let me open in an new issue! @torzdf

**Comment by daniellivingston** [comment]
Related huge news: https://pytorch.org/blog/introducing-accelerated-pytorch-training-on-mac/

**Comment by torzdf** [comment]
It's certainly good news for you M1 owners. TBH if I was starting this project again, I'd probably go PyTorch, but I have no plans to port the code, as it would be a mammoth task.

At some point I'm probably going to update setup.py so M1 owners are pulled in to the same install path as Nvidia/CPU/AMD users.

@daniellivingston @geewiz94 it would be very helpful to me if you could tell me what identifying information I can pull to know that the user is running on an M1 mac (e.g. like 

```py
 platform.system() = "Windows"/"Linux"/"Darwin"
```

but exclusively identifies M1.

**Comment by geewiz94** [comment]
@torzdf I think you're looking for a function like this, for me it outputs `darwin_arm64`: https://stackoverflow.com/a/71551501

Other ways I've tried:
```
>> platform.machine()
arm64
>> platform.processor()
arm
>> cpuinfo.get_cpu_info().get('brand_raw')
Apple M1 Pro
```
I'm not able to test this on an Intel Mac unfortunately.

**Comment by torzdf** [comment]
that's good, thanks. I was hoping to be able to identify just on system, but it's no biggy to get the additional information from the processor.

**Comment by Louisfuk** [comment]
So grateful for this work!
Does this mean we’re closer to DeepFaceLive on M1?

**Comment by zhouhao27** [comment]
Is there a ready made Mac OS executable?

**Pull request merged**
