### PR TITLE
image sort tool and PluginLoader.get_available_models()

### PR DESCRIPTION
**Pull request by iperov**
https://github.com/deepfakes/faceswap/issues/252
usage:
```
python.exe faceswap\sorttool.py -i %WORKSPACE%\data_src\aligned -by similarity
python.exe faceswap\sorttool.py -i %WORKSPACE%\data_src\aligned -by blur
```

### CODE REVIEW

**Comment by bryanlyon** [comment]
A separate tool is helpful, but should also (optionally) modify the alignments.json so that it works with converting the files and not just for training.

**Comment by iperov** [comment]
@bryanlyon why ?

**Comment by iperov** [comment]
I created this tool for myself, and its functionality enough for me.
Anyone can improve it after merge.

**Comment by iperov** [comment]
PluginLoader.get_default_model()
provides easy integration of Model_* folders without changing convert.py and train.py

**Comment by Clorr** [comment]
Nice one ;-) I was also thinking modifying this was getting cumbersome because it makes conflicts everytime.

Just a note though, think about separating pull requests when they are not for the same purpose. Not a big deal here

**Comment by iperov** [comment]
how ? I cannot fork twice.

**Comment by Clorr** [comment]
You have to make a new branch or tag. Here your pull request id for master and if you push on master this Pr is updated automatically. If you do a new branch and make a PR for the branch, you can make separate PR

**Comment by iperov** [comment]
ok thx

**Pull request merged**
