### PR TITLE
Update alignments.py

### PR DESCRIPTION
**Pull request by CaptainStabs**
Added better handling of an already existing alignment file being used in the -al argument

### CODE REVIEW

**Comment by CaptainStabs** [comment]
Not sure if you all actually care about that failing check but that was done prior to this commit [b67f91e].(https://github.com/deepfakes/faceswap/commit/b67f91ea0b9d75bd9a2b1c312eedc7ff2e47a2b1)

**Comment by torzdf** [comment]
> 
> 
> Not sure if you all actually care about that failing check but that was done prior to this commit [b67f91e](https://github.com/deepfakes/faceswap/commit/b67f91ea0b9d75bd9a2b1c312eedc7ff2e47a2b1)

No. That's fine. I pushed the fix when I saw this failing.
What is this PR meant to do exactly? Sorry, I'm a little confused because it shows changes to the legacy landmarks update (now super old code), but references existing alignments files.

Also, please fix the linting errors from pep8speaks nagbot.

**Comment by CaptainStabs** [comment]
> > Not sure if you all actually care about that failing check but that was done prior to this commit [b67f91e](https://github.com/deepfakes/faceswap/commit/b67f91ea0b9d75bd9a2b1c312eedc7ff2e47a2b1)
> 
> What is this PR meant to do exactly? Sorry, I'm a little confused because it shows changes to the legacy landmarks update (now super old code), but references existing alignments files.
> 
> Also, please fix the linting errors from pep8speaks nagbot.

If you input an already existing alignment file, the script will crash with the key error, see [here](https://discord.com/channels/441989398465085440/537225614852227082/793745224953495552)
My PR just adds a warning telling the user that the alignments file that they are attempting to write to already exists.

**Comment by CaptainStabs** [comment]
> > Not sure if you all actually care about that failing check but that was done prior to this commit [b67f91e](https://github.com/deepfakes/faceswap/commit/b67f91ea0b9d75bd9a2b1c312eedc7ff2e47a2b1)
> 
> Also, please fix the linting errors from pep8speaks nagbot.

Fixed

**Comment by torzdf** [comment]
Hi. Thanks for the PR. Sorry it took so long, but I've finally got around to pushing a fix for this: https://github.com/deepfakes/faceswap/commit/ef22c576f66dafdc355876eacf3f32096489dbd9

The issue was actually in part of the extract code (specifically around skipping existing alignments). The fix I have pushed re-enables skipping existing alignments/faces. This PR did help me with where to look though.

Any further issues, please feel free to raise.

Closing this PR as it is superseded by the upstream fix..

**Pull request closed without merging**
