### PR TITLE
GUI v0.1.0a

### PR DESCRIPTION
**Pull request by torzdf**
Please see #325 for more detailed information.

This PR addresses the issues described here: #334

Tested for non installation of python3-tk.
Tested for loading icons when launching outside of the faceswap directory
Cannot test for non-existence of X-Console as I do not have a machine to test on at the moment.

Also, major code refactor (under the hood to aid further development). Very basic error handling for the underlying faceswap.py process.

As before, bugs ahoy, please continue to report and I will continue to address.

### CODE REVIEW

**Comment by fat-tire** [comment]
I'm still seeing this error w/o $DISPLAY set:

```
Traceback (most recent call last):
  File "faceswap.py", line 30, in <module>
    subparser, guiparsers, parser, "gui", "Launch the Faceswap Graphical User Interface.")
  File "/content/faceswap/scripts/gui.py", line 430, in __init__
    self.root = FaceswapGui(self.opts, self.parser)
  File "/content/faceswap/scripts/gui.py", line 49, in __init__
    self.gui = tk.Tk()
  File "/usr/lib/python3.6/tkinter/__init__.py", line 2020, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
```

It looks like check_display() only returns if DISPLAY is set [in cases where "gui" is the first argument](https://github.com/torzdf/faceswap/blob/gui/scripts/gui.py#L41).  In a headless server-type situation, you would NOT include "gui" as an argument, so check_display() always returns True (when gui isn't invoked, if that makes sense.)  In other words, in a headless situation, the check fails checking for "gui".  You shouldn't require "gui" to check for the DISPLAY being set.  put yet another way, the default behavior right now is to assume that DISPLAY *is* set unless proven otherwise by saying "gui" and NOT setting DISPLAY.

You might want to check if gui is any argument rather than just the first BTW.

Finally-- even when I DO add gui as an argument (hoping it would fail due to lack of DISPLAY) to force the check, I get failure on the DISPLAY check:

```
Traceback (most recent call last):
  File "faceswap.py", line 30, in <module>
    subparser, guiparsers, parser, "gui", "Launch the Faceswap Graphical User Interface.")
  File "/content/faceswap/scripts/gui.py", line 425, in __init__
    if not check_display(cmd) or not import_tkinter(cmd):
  File "/content/faceswap/scripts/gui.py", line 41, in check_display
    if command == 'gui' and not environ['DISPLAY']:
  File "/usr/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'DISPLAY'
```

Might you have meant `environ.get('DISPLAY')` rather than `environ('DISPLAY')`?  You can check if it's set to `None` to avoid this crash.  You might debug this by trying something other than DISPLAY (like TESTDISPLAY) that you know has NOT been set.

Hope this helps.

**Comment by bryanlyon** [comment]
One way to fix this would be to encase the call in a try except block.  Make sure you're only capturing the errors that match and let the other errors through.

**Comment by fat-tire** [comment]
I don't think you have to go that far.  Assume that gui is not enabled unless proven otherwise, then:

if any parameter == "gui" and 'DISPLAY' in environ:
    (now import gui stuff and create object...)

**Comment by torzdf** [comment]
Thanks for the feedback. Annoyingly it was the one thing I couldn't test (although I did echo $DISPLAY on a headless machine to see what I would get).  Full Traceback is useful.

**Comment by torzdf** [comment]
Hopefully latest commit got it. Annoyingly I would have caught that I had forgotten to split the GUI check from the DISPLAY check if I'd tested. I only include the GUI check to spit out a useful error message.

I still can't test, but please let me know :)

**Comment by fat-tire** [comment]
Looking forward to it!   Request:  could you add a flag to output that graph to a file?   Request #2-- I think [tensorboard](https://www.tensorflow.org/programmers_guide/summaries_and_tensorboard) counts as GUI right? Maybe add a flag to dump a log every so often so TB can be attached and progress monitored that way too?  Cheers!

**Comment by torzdf** [comment]
I'm trying to avoid faceswap.py having any dependencies on the GUI, or faceswap.py having to have any code to specifically support it. Obviously there is only so far I can go with this approach!

I will look into tensorboard, but in the meantime I'm just looking to generate a graph with matplotlib based on the loss values output to console, as these are trivial to hook into. Saving the graph from the GUI should be straightforward, but it won't work without the GUI. Porting the code to some kind of file writer as part of train.py should be straightforward though, so it could be looked into if we decided that was the way to go.

**Comment by torzdf** [comment]
@bryanlyon @Clorr Is it possible to merge this, as it's a bugfix that will effect anyone using faceswap.py in an headless environment.

Thanks

**Comment by johnc2k** [comment]
I am still getting the message "Could not detect a display. The GUI has been disabled" on Windows 10.
Im assuming I need to define the $DISPLAY variable in Windows?

**Comment by torzdf** [comment]
Arggh. Annoyingly I found this issue when testing today. I can push a fix, or you can ammend gui.py in scripts from:

`if not environ.get('DISPLAY', None):`

to:

`if not os.environ.get('DISPLAY', None) and os.name != 'nt':`

(Line 47)

**Comment by johnc2k** [comment]
That fixed it thanks

**Pull request merged**
