### PR TITLE
Progress bar for DirectoryProcessor and uppercase extension fix.

### PR DESCRIPTION
**Pull request by gdunstone**
progress bar and uppercase extensions.

Added progress bar re https://github.com/deepfakes/faceswap/issues/80
Fixed uppercase extensions re https://github.com/deepfakes/faceswap/issues/75

### CODE REVIEW

**Comment by Irastris** [comment]
Along with `requirements.txt`, the new `tqdm` module should be added to `requirements-gpu.txt` as well.

**Comment by Irastris** [comment]
Also, glad my suggestion is being considered!

**Comment by Clorr** [comment]
Hello,

I've merged my modifications and it creates a conflict. Can you solve this ? I can do it on my side, but not today.

Thanks

**Comment by deepfakes** [comment]
Thanks for the pull request! I invited you as collaborator, feel free to merge this by yourself if youfeel confident enough on your code ;-)

**Comment by gdunstone** [comment]
I added some more fixes and cli args.
I completed the todo in train.py and added a save_now (s key) for the --preview option.

**Comment by gdunstone** [comment]
Thanks!

**Comment by deepfakes** [comment]
Nice ;-)

If you want to take other things, feel free. Just assign yourself where relevant.

**Pull request merged**
