### PR TITLE
Removed functions now implemented in plaidml itself

### PR DESCRIPTION
**Pull request by kilroythethird**
Shouldn't harm anything, but less code to maintain is always a good thing.

### CODE REVIEW

**Comment by learning2makethings** [comment]
What release of plaidml does this require? For reference it's my first time using faceswap so it's highly likely I made a mistake elsewhere. I installed plaidml with pip, without picking a version and I couldn't train without getting the error:
```
ImportError: cannot import name 'extract_image_patches' from 'plaidml.op'
```

I went back and used the old versions of plaidml_utils.py and losses.py that had the needed functions built in and it worked fine. Appreciate the work you guys put in, thanks!

Crash Report
```
06/25/2019 17:19:11 MainProcess     MainThread      plaidml_tools   load_active_devices       DEBUG    Setting PlaidML devices from user_settings
06/25/2019 17:19:11 MainProcess     MainThread      plaidml_tools   setup_plaidml             INFO     Using GPU: []
06/25/2019 17:19:11 MainProcess     MainThread      plaidml_tools   setup_plaidml             INFO     Successfully set up for PlaidML
06/25/2019 17:19:11 MainProcess     MainThread      cli             setup_amd                 DEBUG    setup up for PlaidML
06/25/2019 17:19:12 MainProcess     MainThread      cli             test_for_tf_version       DEBUG    Installed Tensorflow Version: 1.13
06/25/2019 17:19:12 MainProcess     MainThread      train           __init__                  DEBUG    Initializing Train: (args: Namespace(alignments_path_a=None, alignments_path_b=None, allow_growth=False, amd=True, augment_color=False, batch_size=32, configfile=None, func=<bound method ScriptExecutor.execute_script of <lib.cli.ScriptExecutor object at 0x10c3a8978>>, gpus=1, input_a='/Users/hero/Local/Workspace/faceswap/faces_out', input_b='/Users/hero/Local/Workspace/faceswap/goal_out', iterations=1000000, logfile=None, loglevel='INFO', memory_saving_gradients=False, model_dir='/Users/hero/Local/Workspace/faceswap/model', no_flip=False, no_logs=False, pingpong=False, preview=False, preview_scale=50, redirect_gui=False, save_interval=100, snapshot_interval=25000, timelapse_input_a=None, timelapse_input_b=None, timelapse_output=None, trainer='dfaker', warp_to_landmarks=False, write_image=False)
06/25/2019 17:19:12 MainProcess     MainThread      train           get_images                DEBUG    Getting image paths
06/25/2019 17:19:12 MainProcess     MainThread      utils           get_image_paths           DEBUG    Scanned Folder contains 57 files
06/25/2019 17:19:12 MainProcess     MainThread      utils           get_image_paths           DEBUG    Returning 55 images
06/25/2019 17:19:12 MainProcess     MainThread      utils           get_image_paths           DEBUG    Scanned Folder contains 413 files
06/25/2019 17:19:12 MainProcess     MainThread      utils           get_image_paths           DEBUG    Returning 411 images
06/25/2019 17:19:12 MainProcess     MainThread      train           get_images                INFO     Model A Directory: /Users/hero/Local/Workspace/faceswap/faces_out
06/25/2019 17:19:12 MainProcess     MainThread      train           get_images                INFO     Model B Directory: /Users/hero/Local/Workspace/faceswap/goal_out
06/25/2019 17:19:12 MainProcess     MainThread      train           get_images                DEBUG    Got image paths: [('a', '55 images'), ('b', '411 images')]
06/25/2019 17:19:12 MainProcess     MainThread      train           __init__                  DEBUG    Initialized Train
06/25/2019 17:19:12 MainProcess     MainThread      train           process                   DEBUG    Starting Training Process
06/25/2019 17:19:12 MainProcess     MainThread      train           process                   INFO     Training data directory: /Users/hero/Local/Workspace/faceswap/model
06/25/2019 17:19:12 MainProcess     MainThread      utils           set_system_verbosity      DEBUG    System Verbosity level: 2
06/25/2019 17:19:12 MainProcess     MainThread      train           start_thread              DEBUG    Launching Trainer thread
06/25/2019 17:19:12 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initializing MultiThread: (target: 'training', thread_count: 1)
06/25/2019 17:19:12 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initialized MultiThread: 'training'
06/25/2019 17:19:12 MainProcess     MainThread      multithreading  start                     DEBUG    Starting thread(s): 'training'
06/25/2019 17:19:12 MainProcess     MainThread      multithreading  start                     DEBUG    Starting thread 1 of 1: 'training_0'
06/25/2019 17:19:12 MainProcess     MainThread      multithreading  start                     DEBUG    Started all threads 'training': 1
06/25/2019 17:19:12 MainProcess     MainThread      train           start_thread              DEBUG    Launched Trainer thread
06/25/2019 17:19:12 MainProcess     MainThread      train           monitor                   DEBUG    Launching Monitor
06/25/2019 17:19:12 MainProcess     MainThread      train           monitor                   INFO     ===================================================
06/25/2019 17:19:12 MainProcess     MainThread      train           monitor                   INFO       Starting
06/25/2019 17:19:12 MainProcess     MainThread      train           monitor                   INFO       Press 'ENTER' to save and quit
06/25/2019 17:19:12 MainProcess     MainThread      train           monitor                   INFO       Press 'S' to save model weights immediately
06/25/2019 17:19:12 MainProcess     MainThread      train           monitor                   INFO     ===================================================
06/25/2019 17:19:13 MainProcess     training_0      train           training                  DEBUG    Commencing Training
06/25/2019 17:19:13 MainProcess     training_0      train           training                  INFO     Loading data, this may take a while...
06/25/2019 17:19:13 MainProcess     training_0      train           load_model                DEBUG    Loading Model
06/25/2019 17:19:13 MainProcess     training_0      utils           get_folder                DEBUG    Requested path: '/Users/hero/Local/Workspace/faceswap/model'
06/25/2019 17:19:13 MainProcess     training_0      utils           get_folder                DEBUG    Returning: '/Users/hero/Local/Workspace/faceswap/model'
06/25/2019 17:19:13 MainProcess     training_0      plugin_loader   _import                   INFO     Loading Model from Dfaker plugin...
06/25/2019 17:19:14 MainProcess     training_0      multithreading  run                       DEBUG    Error in thread (training_0): cannot import name 'extract_image_patches' from 'plaidml.op' (/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/plaidml/op.py)
06/25/2019 17:19:14 MainProcess     MainThread      train           monitor                   DEBUG    Thread error detected
06/25/2019 17:19:14 MainProcess     MainThread      train           monitor                   DEBUG    Closed Monitor
06/25/2019 17:19:14 MainProcess     MainThread      train           end_thread                DEBUG    Ending Training thread
06/25/2019 17:19:14 MainProcess     MainThread      train           end_thread                CRITICAL Error caught! Exiting...
06/25/2019 17:19:14 MainProcess     MainThread      multithreading  join                      DEBUG    Joining Threads: 'training'
06/25/2019 17:19:14 MainProcess     MainThread      multithreading  join                      DEBUG    Joining Thread: 'training_0'
06/25/2019 17:19:14 MainProcess     MainThread      multithreading  join                      ERROR    Caught exception in thread: 'training_0'
06/25/2019 17:19:14 MainProcess     MainThread      plaidml_tools   initialize                DEBUG    PlaidML already initialized
06/25/2019 17:19:14 MainProcess     MainThread      plaidml_tools   get_supported_devices     DEBUG    []
06/25/2019 17:19:14 MainProcess     MainThread      plaidml_tools   get_all_devices           DEBUG    Experimental Devices: []
06/25/2019 17:19:14 MainProcess     MainThread      plaidml_tools   get_all_devices           DEBUG    []
06/25/2019 17:19:14 MainProcess     MainThread      plaidml_tools   __init__                  DEBUG    Initialized: PlaidMLStats
Traceback (most recent call last):
  File "/Users/hero/Local/Workspace/faceswap/lib/cli.py", line 124, in execute_script
    process.process()
  File "/Users/hero/Local/Workspace/faceswap/scripts/train.py", line 98, in process
    self.end_thread(thread, err)
  File "/Users/hero/Local/Workspace/faceswap/scripts/train.py", line 123, in end_thread
    thread.join()
  File "/Users/hero/Local/Workspace/faceswap/lib/multithreading.py", line 460, in join
    raise thread.err[1].with_traceback(thread.err[2])
  File "/Users/hero/Local/Workspace/faceswap/lib/multithreading.py", line 390, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/hero/Local/Workspace/faceswap/scripts/train.py", line 149, in training
    raise err
  File "/Users/hero/Local/Workspace/faceswap/scripts/train.py", line 137, in training
    model = self.load_model()
  File "/Users/hero/Local/Workspace/faceswap/scripts/train.py", line 156, in load_model
    model = PluginLoader.get_model(self.trainer_name)(
  File "/Users/hero/Local/Workspace/faceswap/plugins/plugin_loader.py", line 26, in get_model
    return PluginLoader._import("train.model", name, disable_logging)
  File "/Users/hero/Local/Workspace/faceswap/plugins/plugin_loader.py", line 47, in _import
    module = import_module(mod)
  File "/Users/hero/Local/Workspace/faceswap/plaidml/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/hero/Local/Workspace/faceswap/plugins/train/model/dfaker.py", line 10, in <module>
    from .original import logger, Model as OriginalModel
  File "/Users/hero/Local/Workspace/faceswap/plugins/train/model/original.py", line 10, in <module>
    from ._base import ModelBase, logger
  File "/Users/hero/Local/Workspace/faceswap/plugins/train/model/_base.py", line 23, in <module>
    from lib.model.losses import DSSIMObjective, PenalizedLoss
  File "/Users/hero/Local/Workspace/faceswap/lib/model/losses.py", line 18, in <module>
    from plaidml.op import extract_image_patches
ImportError: cannot import name 'extract_image_patches' from 'plaidml.op' (/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/plaidml/op.py)

============ System Information ============
encoding:            UTF-8
git_branch:          master
git_commits:         e2ed465 Fix typo. 9265b64 GUI Fixups. 529743a AMD Support - Merge pull request #774 from deepfakes/plaidml. e6653dd Disable parallel processing when non-amd user uses a Keras extractor + non Keras extractor. f5adc99 AMD Support for Manual Tool
gpu_cuda:            Unsupported OS
gpu_cudnn:           Unsupported OS
gpu_devices:         
gpu_devices_active:  
gpu_driver:          []
gpu_vram:            
os_machine:          x86_64
os_platform:         Darwin-18.6.0-x86_64-i386-64bit
os_release:          18.6.0
py_command:          faceswap.py train -A /Users/hero/Local/Workspace/faceswap/faces_out -B /Users/hero/Local/Workspace/faceswap/goal_out -m /Users/hero/Local/Workspace/faceswap/model -bs 32 -amd -t dfaker
py_conda_version:    N/A
py_implementation:   CPython
py_version:          3.7.3
py_virtual_env:      True
sys_cores:           4
sys_processor:       i386
sys_ram:             Total: 16384MB, Available: 8343MB, Used: 7193MB, Free: 1984MB

=============== Pip Packages ===============
absl-py==0.7.1
astor==0.8.0
certifi==2019.6.16
cffi==1.12.3
chardet==3.0.4
Click==7.0
colorama==0.4.1
cycler==0.10.0
decorator==4.4.0
enum34==1.1.6
fastcluster==1.1.25
ffmpy==0.2.2
gast==0.2.2
google-pasta==0.1.7
grpcio==1.21.1
h5py==2.9.0
idna==2.8
imageio==2.5.0
imageio-ffmpeg==0.3.0
joblib==0.13.2
Keras==2.2.2
Keras-Applications==1.0.4
Keras-Preprocessing==1.0.2
kiwisolver==1.1.0
Markdown==3.1.1
matplotlib==2.2.2
mock==3.0.5
networkx==2.3
numpy==1.16.2
nvidia-ml-py3==7.352.0
opencv-python==4.1.0.25
pathlib==1.0.1
Pillow==6.0.0
plaidbench==0.6.1
plaidml==0.6.1
plaidml-keras==0.6.1
protobuf==3.8.0
psutil==5.6.3
pycparser==2.19
pynvx==1.0.0
pyparsing==2.4.0
python-dateutil==2.8.0
pytz==2019.1
PyWavelets==1.0.3
PyYAML==5.1.1
requests==2.22.0
scikit-image==0.15.0
scikit-learn==0.21.2
scipy==1.3.0
six==1.12.0
tensorboard==1.13.1
tensorflow==1.13.1
tensorflow-estimator==1.13.0
termcolor==1.1.0
toposort==1.5
tqdm==4.32.2
urllib3==1.25.3
Werkzeug==0.15.4
wrapt==1.11.2
```

**Comment by kilroythethird** [comment]
It is in plaidml==0.6.1 which you seem to have.
So they might have build the wrong release for mac os.
Just to be sure can you try to update it anyway:

`pip install -U --force-reinstall plaidml==0.6.1 plaidml-keras==0.6.1`

**Comment by kilroythethird** [comment]
I did read your log again and it seems plaidml doesn't detect any gpu on your system.
I have no clue why it would work after you replaced the plaidml_utils.py and losses.py without changing your installed plaidml version to be honest.

But can you please run
`plaidml-setup` and post the result in here ?

**Comment by learning2makethings** [comment]
Here is the plaidml-setup results, and I am using the AMD Radeon VII (Metal) to train as I type this. 

```
(plaidml) 22:09:29 ~/Local/Workspace/faceswap $ plaidml-setup

PlaidML Setup (0.6.1)

Thanks for using PlaidML!

Some Notes:
  * Bugs and other issues: https://github.com/plaidml/plaidml
  * Questions: https://stackoverflow.com/questions/tagged/plaidml
  * Say hello: https://groups.google.com/forum/#!forum/plaidml-dev
  * PlaidML is licensed under the Apache License 2.0
 
Default Config Devices:
   metal_intel(r)_iris(tm)_graphics_6100.0 : Intel(R) Iris(TM) Graphics 6100 (Metal)
   metal_amd_radeon_vii.0 : AMD Radeon VII (Metal)

Experimental Config Devices:
   llvm_cpu.0 : CPU (LLVM)
   opencl_cpu.0 : Intel CPU (OpenCL)
   opencl_intel_iris(tm)_graphics_6100.0 : Intel Inc. Intel(R) Iris(TM) Graphics 6100 (OpenCL)
   opencl_amd_radeon_vii_compute_engine.0 : AMD AMD Radeon VII Compute Engine (OpenCL)
   metal_intel(r)_iris(tm)_graphics_6100.0 : Intel(R) Iris(TM) Graphics 6100 (Metal)
   metal_amd_radeon_vii.0 : AMD Radeon VII (Metal)

Using experimental devices can cause poor performance, crashes, and other nastiness.

Enable experimental device support? (y,n)[n]:
```

Here is the output when I start training, which is also a bit strange. As you can see it says "Using GPU: []" but then later shows "Opening device "metal_amd_radeon_vii.0"".

```
06/25/2019 22:15:25 INFO     Log level set to: INFO
06/25/2019 22:15:25 INFO     Setting up for PlaidML
06/25/2019 22:15:25 INFO     Using GPU: []
06/25/2019 22:15:25 INFO     Successfully set up for PlaidML
Using plaidml.keras.backend backend.
06/25/2019 22:15:31 INFO     Model A Directory: /Users/hero/Local/Workspace/faceswap/facesA
06/25/2019 22:15:31 INFO     Model B Directory: /Users/hero/Local/Workspace/faceswap/facesB
06/25/2019 22:15:31 INFO     Training data directory: /Users/hero/Local/Workspace/faceswap/model
06/25/2019 22:15:31 INFO     ===================================================
06/25/2019 22:15:31 INFO       Starting
06/25/2019 22:15:31 INFO       Using live preview
06/25/2019 22:15:31 INFO       Press 'ENTER' to save and quit
06/25/2019 22:15:31 INFO       Press 'S' to save model weights immediately
06/25/2019 22:15:31 INFO     ===================================================
06/25/2019 22:15:32 INFO     Loading data, this may take a while...
06/25/2019 22:15:32 INFO     Loading Model from Villain plugin...
06/25/2019 22:15:34 INFO     Using configuration saved in state file
06/25/2019 22:15:34 INFO     Opening device "metal_amd_radeon_vii.0"
06/25/2019 22:15:37 INFO     Opening device "metal_amd_radeon_vii.0"
```

I've verified the amd gpu is actually being used by watching its processor and memory usage. The training speed seems to be about what I expect. I was having [this](https://github.com/plaidml/plaidml/issues/245#issuecomment-502730000) issue earlier and fixed it so maybe it's related?

**Comment by kilroythethird** [comment]
The issue you linked could definitely be related.
I think you have two different plaidml versions installed.
You could check this maybe by running
```
import plaidml
plaidml.__version__
```
in your venv. and additionally check if `/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/plaidm/op.py` has the `extract_image_patches` function/variable. If not that is indeed an old plaidml version.
If my assumption is correct that is nothing where we can really help, sorry.

**Pull request merged**
