### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Aneal-Sharma**
-fixed some grammatical errors
-improved word choice

### CODE REVIEW

**Comment by gessyoo** [comment]
You should proofread this again.  For example, the abbreviation is Ph.D. not PhD.

**Comment by Aneal-Sharma** [comment]
Both abbreviations are valid. Which one do you prefer?

**Comment by torzdf** [comment]
PhD is fine.

**Comment by Aneal-Sharma** [comment]
> PhD is fine.

Can you merge?

**Comment by torzdf** [comment]
I need to review first. I will once I get a chance

**Pull request merged**
