### PR TITLE
Adding models as plugins + Face filtering (#53) + #39 + #43 + #44 + #49

### PR DESCRIPTION
**Pull request by Clorr**
This is a new Pull request that is without the GAN plugin that is still a work in progress

This PR features a couple of refactorings and bug corrections + the models as plugins

The main new feature is the face filtering that will only extract and convert recognized faces. For that, you have to add a filter.jpg with a face of the person you want to retain in the current working dir. (An argument should be created later to specify the name of the file)

### CODE REVIEW

**Comment by Clorr** [comment]
This PR should be ready to merge, contrary to other [DRAFT] PRs

**Comment by Clorr** [comment]
Hi @Ganonmaster !

Happy to see you have some time for review! For me it is a bit hard because I only have an old iMac to program for these days and it's a hell to run this monster ;-)

I hope you can merge this soon, so we can quickly move on to the GAN version ;-)

I am a bit busy now, but if you have small changes to do, tell them here, and I'll see if I can do a quick fix before I leave...

**Comment by Clorr** [comment]
I sent you a collab invite on my repo, if you have fixes to push to my master now you can fix it directly if you want...

**Comment by Ganonmaster** [comment]
The training preview is broken. My guess would be that the image window can only be updated from the main thread.

**Comment by Clorr** [comment]
Hmm that's a bit annoying since I can't have preview window as I'm working with docker. I'll try with that link when I can  : https://stackoverflow.com/questions/44577228/multithreaded-cv2-imshow-in-python-does-not-work

**Comment by Ganonmaster** [comment]
Writing sample still works, but somehow it seems to save it much darker than it should.
_sample

**Comment by Clorr** [comment]
Ok, any clue about where it can com from?

**Comment by Clorr** [comment]
Maybe it comes from the read_image in training_data.py I took from the Gan version. It makes "/ 255 * 2 -1" this makes images darker. I have to see why it's done like that...

**Comment by Clorr** [comment]
Hi guys,

I'm not fully settled yet, but I start having a bit more time for coding ;-) Also I should be finished in a couple of days with my new PC on which I will have a linux and a windows, but mostly a 8gb 1070 Geforce ^^

Btw I pushed a modification for the "darker" images, which was coming from the gan repo merge. I think it is ok, but you should confirm.

Also I tried a new preview approach, but it is not tested as I'm still running on my imac+docker setup

Let me know if you see something I should change...

**Comment by Clorr** [comment]
I'm getting closer! Now I have a preview window to test ;-)
screenshot-nomachine

**Comment by Apollo122** [comment]
Welcome back @Clorr 
Waiting for GAN progress :)
Nice setup you have there btw

**Comment by Clorr** [comment]
Once this is merged, I'll be able to work full time on GAN, so it should move on faster now.

I will also have a look at the overall performance, because I'm surprised the cpu gets so much load...

**Comment by jondubin** [comment]
Awesome, glad to have you back @Clorr. Excited to see this and GAN merged in

**Comment by Clorr** [comment]
I'm merging this since I tested it on my side. Feel free to report any problem if any.

**Pull request merged**
