### PR TITLE
OriginalHighRes 128 model update

### PR DESCRIPTION
**Pull request by andenixa**
Required for OriginalHighRes Model to function

### CODE REVIEW

**Comment by andenixa** [comment]
@Kirin-kun thats confirmed for 6GB cards. Shall be fixed ASAP.

**Comment by andenixa** [comment]
@Kirin-kun I apologize for not testing with 6Gb card prior to make a PR.
Currently I made a PR to staging but you are welcome to test is. I've am able to train it at 6GB gforce gtx9800ti with maximum batch_size of 12. That should be sufficient for good results. 
I could squeeze memory requirements much further, but my intentions were to provide a full scale 128x128 model and I don't want to make a crippled version of it.

**Comment by Kirin-kun** [comment]
Is your original encoder 128 better than, or equivalent to, Iperov's H128?

I got pretty good results with his model.

**Comment by andenixa** [comment]
@Kirin-kun I don't think you have Iperov's H128 with faceswap. You need to use DeepFaceLab for that.
I should think Iperov models are better, specially F128 ones. Definitely faster with his new K.function design. Then again you need another repo to use it. I don't know for sure because I never used his pure H128, 
I made an HD mod with 192x192 tensor size and Shaonlu activation based on Iperov's H128 so I can't compare to the original one (because I don't have any trained Iperov's H128 on hands).

**Pull request merged**
