### PR TITLE
New control for training.sh loop

### PR DESCRIPTION
**Pull request by GSonderling**
Per the issue #207 submitted by me. I present following change to behavior of main training loop.

In interest of simplicity, I decided to drop the `'Enter'` interrupt entirely, and switch to more traditional `Ctrl + C`.
Additionally, this approach requires no further imports. Thus keeping the code clean and simple. 

It also gets rid of hanging, that sometimes occurs after training is finished.

### CODE REVIEW

**Comment by babilio** [comment]
Enter works fine and reliably for me when I have the preview window and you focus on it before pressing. I am not sure removing it completely is good thing. Couldn't Ctrl+C just stop mid saving weights, potentially corrupting model files?

**Comment by luiscosio** [comment]
I agree that Ctrl + C is better than ENTER and all the difference between keys in OS.

**Comment by GSonderling** [comment]
Oops, I just realized I overlooked indent. 

Anyway, if you look at the code, after I fix it, you can see that the preview window still behaves as it did before. You can still stop it with `Enter`.

**Comment by GSonderling** [comment]
Ok, fix submitted and tested.

**Comment by Clorr** [comment]
Maybe also related to #116

**Comment by GSonderling** [comment]
Any suggestions? Would anyone like something added or changed? Did you find any undesirable behavior?

**Comment by Clorr** [comment]
For me it seems ok, but I haven't tested yet. I could not work on the project lately, but I'm starting to get some more free time so I hope to give you a feedback soon...

**Comment by iperov** [comment]
>  I decided to drop the 'Enter' interrupt entirely.

you decided ? How about existing FaceSwap end-users ? Not developers, users.

**Comment by 3xtr3m3d** [comment]
its printing 
> Starting. Press "Ctrl + C" to stop training and save model
so end-users know what to do though

**Comment by GSonderling** [comment]
> you decided ? How about existing FaceSwap end-users ? Not developers, users.

If people don't like it there is no need to accept the PR. But right now the script behaves rather strangely, wouldn't you agree?

It basically just waits for any input followed by `Enter` and if there is none it just hangs. That is a little confusing. 

And for the record, I agree that my fix is not exactly the most elegant or optimal. I would prefer to get rid of those exceptions completely and just use normal key press events.

But all the solutions I tried, and that worked, involved either further imports, which would confuse the users, more threads, which is just an overkill, or worse of all bunch of code that is there just to handle one event.

Now, I don't want to cause problems by making unwanted changes to the code. So how about this, lets go to the playground and put it to vote, so that users decide what kind of behavior they want.

**Comment by Clorr** [comment]
No problem @GSonderling . `Enter` is certainly more natural for very new users, but beside of that is not of a strong interest. `Ctrl + c` adds convenience for usage in special conditions, like notebooks or remote run.

**Comment by GSonderling** [comment]
The enter still works for windowed preview, which is what most new users use, I assume.

**Comment by 3xtr3m3d** [comment]
this is good for cloud training like google colaboratory. please merge this

**Comment by bryanlyon** [comment]
I prefer using something a bit more high level than input().  I suggest something like

if cv2.waitKey(1) & 0xFF == 13:
        break

This will break the loop if the 'enter' key is pressed in the window but will not block on ctrl-c.

**Comment by torzdf** [comment]
This has been somewhat mitigated by the latest refactor. I agree that hanging for input is not ideal, but ctrl+c will also terminate the training loop, so there are options, until something better comes along.

This code is now also somewhat behind the current repo, so I'm closing for now. Feel free to re-open against the latest base.

**Pull request closed without merging**
