### PR TITLE
Allow users to swap the A/B models

### PR DESCRIPTION
**Pull request by Ganonmaster**
Also made the aligner optional/toggleable. I have yet to test these changes.

### CODE REVIEW

**Comment by Yutsa** [comment]
It looks great. Were we using the aligner before ?

**Comment by Ganonmaster** [comment]
The aligner was not ready, that's why the default setting is off. Having it as an option should make testing improvements for it easier though.

**Comment by Yutsa** [comment]
What does it align exactly ? How does it improve the results ? Sorry for my ignorance

**Comment by Ganonmaster** [comment]
IF you look at the script in its current form, it simply crops a straight rectangle and applies the transformation to that + pastes it back. However, sometimes a head is tilted sideways and we could get a better crop if we rotated the cropped image for example. That's what the aligner is for. It's kind of rough in its current state, that's why it was commeted out.

**Comment by Ganonmaster** [comment]
I just tested this latest pull request, and it seems to be functioning accordingly.

**Pull request merged**
