### PR TITLE
fix #233, #237, + working with any batch size

### LINKED ISSUE #233: Some faces with one eye hair covered can't be recognized
*First THANKS A LOT for all contributors' hard work!
*Always make a compare test after big change, test with same source 1000 pics (kar801 -> kar1800) , compare with FakeApp1.1 & latest faceswap commit 232d931. 
*Test files (this is porn, sorry~) :  https://drive.google.com/open?id=1DKP0Uci97FfriuKcYEbDT2Qp6rKN1h1g

## Expected behavior
Not sure, limitation ? or possible to improve ? 

## Actual behavior
FakeApp1.1 extract rate is 988/1000
faceswap -D cnn extract rate is 943/1000

comparetest

Notice that some faces - specially one eye covered by hair can't be extract. Example: kar1086 -> kar1090, these 5 pics can be extract normally in FakeApp, but failed in faceswap. Compare kar1085 with kar1086, no big gap in these 2 pics, just corner of the eye be covered by hair in kar1086.  

## Steps to reproduce
python faceswap.py extract -i D:/project4/data_A1/ -o D:/project4/data_A1/output/ -D cnn

## Other relevant information

- **Operating system and version:** Windows, macOS, Linux 
Windows10
Python3.6.4
CUDA9.0
dlib 19.9
The others env same as requirements-gpu-python36-cuda9.txt

### LINKED ISSUE #237: Latest commit extraction fails: Expected numpy.ndarray of uint8
The commit before with the memory issue extracts other than memory issues on lower end GPUs. (I guess 2GB cards will not work anymore for extractions, even with the memory fix?)

I tested the newest commit with the memory fix and I get the above error thrown by the extraction error handler. I tested jpg, png, 2 sets of hardware with 2 different conda environments. I verified the commit before, and 2 commits before worked fine on all the hardware and data sets.

Maybe I am missing something obvious with the newest commit.

### PR DESCRIPTION
**Pull request by iperov**
fix #233 - primordial bug when dlib recognizes less faces than FakeApp, reason: rgb-bgr order affects chance of face recognition. Numpy.imread and cv2.imread loads same image in different rgb-bgr order.

fix #237

fix working with any batch size
batch size = 1

python_2018-03-02_19-01-59

2:

python_2018-03-02_19-02-37

3:

python_2018-03-02_19-03-18

 etc

### CODE REVIEW

**Comment by iperov** [comment]
@Clorr hot fixes

**Comment by iperov** [comment]
wait...

**Comment by iperov** [comment]
@Clorr hot fixes

**Comment by Clorr** [comment]
Merged. Thanks for the good work ;-)

**Pull request merged**
